
project_id = "xltugnmjbcowsuwzkkni"

[functions.customer-portal]
verify_jwt = true

[functions.create-payment]
verify_jwt = false

[functions.check-email-availability]
verify_jwt = false

[functions.update-user-email]
verify_jwt = true
