
project_id = "xltugnmjbcowsuwzkkni"

[functions.customer-portal]
verify_jwt = true

[functions.create-payment]
verify_jwt = false

[functions.check-email-availability]
verify_jwt = false

[functions.update-user-email]
verify_jwt = true

[functions.create-user-from-payment]
verify_jwt = false

[functions.update-member]
verify_jwt = true

[functions.create-member]
verify_jwt = true

[functions.delete-member]
verify_jwt = true

[functions.get-stripe-details]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.whatsapp-proxy]
verify_jwt = false
